general:
  camera_model:               'zed'
  camera_name:                'zed'

depth:
  min_depth:                  0.7             # Min: 0.3, Max: 3.0 - Default 0.7 - Note: reducing this value wil require more computational power and GPU memory
  max_depth:                  20.0            # Max: 40.0
