world_frame: "map"
odom_frame: "odom"
rover_frame: "base_link"
use_odom_frame: false

gps_linearization:
  reference_point_latitude: 42.293195
  reference_point_longitude: -83.7096706
  reference_point_altitude: 234.1
