name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: umrover1/ros:latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update -y && rosdep update
      - uses: betwo/github-setup-catkin@master
        with:
          ros-version: "noetic"
          build-tool: "catkin_tools"
          workspace: "$GITHUB_WORKSPACE"
      - run: catkin build
      - run: catkin test
